{
  "total_vulnerabilities": 3,
  "critical_vulnerabilities": 1,
  "high_vulnerabilities": 0,
  "medium_vulnerabilities": 2,
  "low_vulnerabilities": 0,
  "info_vulnerabilities": 0,
  "fixable_vulnerabilities": 2,
  "last_evaluation_time": "2021-09-10T16:38:35.235Z",
  "image": {
    "image_info": {
      "image_digest": "sha256:377a76c823fd4743158290ab9b7c2ce1f45daa7ab085411f90f632e6a307af12",
      "image_id": "sha256:b1e8d8c40b918d3a3fd402d2b8cb78fc45991b460a908f9b63a80bffb526a5b8",
      "registry": "remote_scanner",
      "repository": "securethecloud/my-tweet-app-lacework",
      "created_time": "2021-09-09T15:28:22.944Z",
      "size": 73025599,
      "tags": [
        "latest"
      ]
    },
    "image_layers": [
      {
        "hash": "sha256:691ab7bb77b9e4904bcd889db77af45e021b1ad1ab76ec97f70742fd823a1124",
        "created_by": "ADD file:c5377eaa926bf412dd8d4a08b0a1f2399cfd708743533b0aa03b53d14cb4bb4e in / ",
        "packages": [
          {
            "name": "apk-tools",
            "namespace": "alpine:v3.10",
            "version": "2.10.6-r0",
            "vulnerabilities": [
              {
                "name": "CVE-2021-36159",
                "description": "",
                "severity": "Critical",
                "link": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-36159",
                "fix_version": "2.10.7-r0",
                "metadata": {
                  "NVD": {
                    "CVSSv2": {
                      "PublishedDateTime": "2021-08-03T14:15Z",
                      "Score": 6.4,
                      "Vectors": "AV:N/AC:L/Au:N/C:P/I:N/A:P"
                    },
                    "CVSSv3": {
                      "ExploitabilityScore": 3.9,
                      "ImpactScore": 5.2,
                      "Score": 9.1,
                      "Vectors": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:H"
                    }
                  }
                }
              }
            ]
          }
        ]
      },
      {
        "hash": "sha256:50c3b6197e7ec182ce1265e97e0c17794c476311fb61d3faa1becb30ca19d681",
        "created_by": "RUN apk add --update py2-pip # buildkit",
        "packages": []
      },
      {
        "hash": "sha256:36978e00d4f2a969790ef724c9cf353cdb3afee25fe5cd40d20b1784fa285127",
        "created_by": "RUN pip install --upgrade pip # buildkit",
        "packages": [
          {
            "name": "pip",
            "namespace": "python",
            "version": "20.3.4",
            "vulnerabilities": [
              {
                "name": "CVE-2018-20225",
                "description": "An issue was discovered in pip (all versions) because it installs the version with the highest version number, even if the user had intended to obtain a private package from a private index. This only affects use of the '--extra-index-url' option, and exploitation requires that the package does not already exist in the public index (and thus the attacker can put the package there with an arbitrary version number).",
                "severity": "Medium",
                "link": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-20225",
                "fix_version": "",
                "metadata": {
                  "NVD": {
                    "CVSSv2": {
                      "PublishedDateTime": "2020-05-08T18:15Z",
                      "Score": 6.8,
                      "Vectors": "AV:N/AC:M/Au:N/C:P/I:P/A:P"
                    },
                    "CVSSv3": {
                      "ExploitabilityScore": 1.8,
                      "ImpactScore": 5.9,
                      "Score": 7.8,
                      "Vectors": "CVSS:3.0/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H"
                    }
                  }
                }
              }
            ]
          }
        ]
      },
      {
        "hash": "sha256:5b00bf6cbe11745af0a706a461a0c4ff6c139d43e3480599333e0dabbbee9da3",
        "created_by": "COPY requirements.txt /usr/src/app/ # buildkit",
        "packages": []
      },
      {
        "hash": "sha256:634e0b74ac11e65ac0b65875edcf39a2e70cd459278cbc1e430488430a2a487e",
        "created_by": "RUN pip install --no-cache-dir -r /usr/src/app/requirements.txt # buildkit",
        "packages": [
          {
            "name": "flask",
            "namespace": "python",
            "version": "0.12.3",
            "vulnerabilities": [
              {
                "name": "CVE-2019-1010083",
                "description": "Denial of Service due to unexpected memory usage in the Pallets Project Flask",
                "severity": "Medium",
                "link": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-1010083",
                "fix_version": "1.0",
                "metadata": {
                  "NVD": {
                    "CVSSv2": {
                      "PublishedDateTime": "2019-07-17T14:15Z",
                      "Score": 5,
                      "Vectors": "AV:N/AC:L/Au:N/C:N/I:N/A:P"
                    },
                    "CVSSv3": {
                      "ExploitabilityScore": 3.9,
                      "ImpactScore": 3.6,
                      "Score": 7.5,
                      "Vectors": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
                    }
                  }
                }
              }
            ]
          }
        ]
      },
      {
        "hash": "sha256:7a775942c0e0513e5dace70459e0b0cc4bece8063b08fbd99fc45ed11db877b2",
        "created_by": "COPY app.py /usr/src/app/ # buildkit",
        "packages": []
      },
      {
        "hash": "sha256:d642cb9b9da0ce4d487bfe3275547a3f072bded69b837523e1eec68482c017d6",
        "created_by": "COPY templates/index.html /usr/src/app/templates/ # buildkit",
        "packages": []
      }
    ]
  },
  "scan_status": "Success"
}
